### ISSUE TITLE
Add Linter Workflow and Separate File for Custom Errors

### ISSUE THREAD

**Issue by malik672** [primitivefinance/arbiter-univ3#5]
Issue Description:

Objective:
To enhance the current workflow by integrating a linter and organizing custom errors into a separate file for better code quality and maintainability.

Details:

Linter Integration:

Integrate a linter into the project workflow to ensure code consistency and identify potential issues early in the development process.
Configure the linter to enforce coding standards and best practices specific to the project.
Separate File for Custom Errors:

Create a separate file to house custom error definitions for improved code organization and readability.

**Comment by Autoparallel** [comment]
@malik672 it seems like I made a bit of a redundant issue with #6 . 

Do you want to do this? It would be greatly appreciated! Arbiter's CI is pretty slim and works well for us. We could just clone that over. What do you think?

**Comment by malik672** [comment]
@Autoparallel will do that

**Comment by Autoparallel** [comment]
How is this going? I saw you had a PR closed. We seem to have some CI added, do you want to make any modifications?

**Comment by malik672** [comment]
let me check

**Comment by malik672** [comment]
one for the linter would be good
